---
- name: '[External Secrets] Adjust RBAC'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - ./templates/rbac.yml.j2

- name: '[External Secrets] Create namespace'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - ./templates/namespace.yml.j2

- name: '[External Secrets] Removing AWS credentials'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: absent
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - ./templates/aws_credential_request.yml

- pause:
    seconds: 5

- name: '[External Secrets] Request AWS credentials'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - ./templates/aws_credential_request.yml

- pause:
    seconds: 15

- name: '[External Secrets] Get AWS credentials'
  k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    kind: secret
    name: aws-credentials
    namespace: "{{ esecret_namespace }}"
  register: aws_credentials

- name: '[External Secrets] Set facts aws_credentials '
  set_fact:
    esecret_aws_id: "{{ aws_credentials.resources.0.data.aws_access_key_id  }}"
    esecret_aws_key: "{{ aws_credentials.resources.0.data.aws_secret_access_key  }}"

- name: '[External Secrets] Aws credentials secret on Openshift '
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - ./templates/aws_secret_back.yml.j2

