apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: external-secret
  namespace: openshift-cloud-credential-operator
spec:
  secretRef:
    name: aws-credentials
    namespace: {{ esecret_namespace }}
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      action:
      - secretsmanager:GetResourcePolicy
      - secretsmanager:GetSecretValue
      - secretsmanager:DescribeSecret
      - secretsmanager:ListSecretVersionIds
      resource: "*"
